### ISSUE TITLE
Is it possible for me to add my own solver?

### ISSUE THREAD

**Issue by fightingxiaoxiao** [gerlero/openfoam-app#72]
I noticed that OpenFOAM installed using this repository is on a read-only system, is there a way to compile and generate external solvers or libraries?

**Comment by fightingxiaoxiao** [comment]
This is a silly question, as OpenFOAM-v2206 that was directly compiled on a new volume works perfectly...

**Comment by gerlero** [comment]
If you **need** a user-writable OpenFOAM installation, you can:
* Compile OpenFOAM yourself from scratch (see the build instructions in the README)
* Convert/copy the OpenFOAM disk image bundled inside the app into a read-write volume (in this case, you need to keep the same volume name so that paths don't change)

Note that user-writeable OpenFOAM install should not actually be needed in order to compile and install either your own or any third-party solvers or libraries—those can (and probably should) be installed into the `$FOAM_USER_APPBIN` directory (with shared libraries going into `$FOAM_USER_LIBBIN`), which are user-writable. See [this](https://github.com/phorgue/porousMultiphaseFoam) for an example of a third-party project that compiles and installs its solvers into the `$FOAM_USER_`* directories.

These issues might also be relevant: https://github.com/gerlero/openfoam-app/issues/25, https://github.com/gerlero/openfoam-app/issues/46

**Comment by fightingxiaoxiao** [comment]
Thanks you very much! It seems like a smart idea to modify the environment variables.

**Comment by gerlero** [comment]
> Thanks you very much! It seems like a smart idea to modify the environment variables.

Do you mean changing the values of the environment variables on your side, or changing the defaults of the app? If the latter, please open a new issue.
