### ISSUE TITLE
icoFoam runs, cartesianMesh does not

### ISSUE THREAD

**Issue by gregnordin** [gerlero/openfoam-app#88]
System: MacBook Pro M1 Max with latest XCode version (13.4.1), command line tools, and system software (macOS Monterey 12.5.1).

After activating `openfoam2206`, I can run an Openfoam solver such as `icoFoam` and get the expected results, but when I try the cfMesh utility, `cartesianMesh`, I get the following error:

```
$ cartesianMesh
dyld[80479]: symbol not found in flat namespace (___kmpc_barrier)
Abort trap: 6
```

Both commands are in the same `bin` directory,

```
$ which icoFoam
/Volumes/OpenFOAM-v2206/platforms/darwin64ClangDPInt32Opt/bin/icoFoam
$ which cartesianMesh
/Volumes/OpenFOAM-v2206/platforms/darwin64ClangDPInt32Opt/bin/cartesianMesh
```
which is in the PATH variable. Here are the first items in PATH:

```
/Volumes/OpenFOAM-v2206/usr/opt/adios2/bin
/Users/nordin/OpenFOAM/nordin-v2206/platforms/darwin64ClangDPInt32Opt/bin
/Volumes/OpenFOAM-v2206/site/2206/platforms/darwin64ClangDPInt32Opt/bin
/Volumes/OpenFOAM-v2206/platforms/darwin64ClangDPInt32Opt/bin
/Volumes/OpenFOAM-v2206/bin
/Volumes/OpenFOAM-v2206/wmake
/Volumes/OpenFOAM-v2206/usr/bin
/opt/homebrew/bin
/opt/homebrew/sbin
...
```

I don't really know where to go from here. It looks like maybe a library is missing that cartesianMesh depends on?

**Comment by gerlero** [comment]
I can confirm that this bug exists, and have been able to track it down to a missing wmake directive in the OpenFOAM source code.

The [`meshLibrary/Make/options` in cfMesh](https://develop.openfoam.com/Development/openfoam/-/issues/1656) should have `$(LINK_OPENMP)` in its `LIB_LIBS` list (see [OpenFOAM issue that introduced the `COMP_OPENMP` and `LINK_OPENMP` definitions](https://develop.openfoam.com/Development/openfoam/-/issues/1656) and [an example of an `options` file that uses them both correctly](https://develop.openfoam.com/Development/openfoam/-/blob/master/src/parallel/decompose/kahipDecomp/Make/options)).

Otherwise, cfMesh binaries are built without the required references the OpenMP dynamic libraries (I've confirmed this with Apple's `otool`), which causes the `symbol not found` error when trying to launch those binaries.

**Comment by gregnordin** [comment]
I looked at references you linked, but am unsure how to fix things. A few days ago I also tried building from source as referenced in your README, and that similarly fails to produce a working `cartesianMesh`. Can the relevant source or make file be updated as part of your make build process to overcome the bug?

**Comment by gerlero** [comment]
I've filed an issue upstream (in the cfMesh-integration repository) at https://develop.openfoam.com/Community/integration-cfmesh/-/issues/8.

Even if this gets fixed upstream, I don't expect a fix for this to arrive before the next OpenFOAM major version (i.e., v2212 in December).

A workaround that should work right now is to patch that file manually (for instance, `make build` then mount the intermediate `OpenFOAM-v****-build.sparsebundle` disk image, add the missing `$(LINK_OPENMP)` in the `modules/cfmesh/meshLibrary/Make/options` file in the right place, `source /Volumes/OpenFOAM-v****/etc/bashrc && /Volumes/OpenFOAM-v****/Allwmake` to recompile cfMesh the change, and finally `make` to finish making the app with these changes).

> Can the relevant source or make file be updated as part of your make build process to overcome the bug?

I've tried as much as possible to avoid patching OpenFOAM source code as part of the build process of OpenFOAM.app, but I agree that this is an instance where it's just a single line and it would allow otherwise broken functionality to work. In any case, I'd have to figure out a way to do this patching somewhat reliably, so a fix for this issue as part of OpenFOAM.app won't happen immediately.

**Comment by gregnordin** [comment]
I downloaded and built the latest version and can confirm that `cartesianMesh` runs and gives the same results for a simple test case as I got using the Docker Openfoam version. I'll let you know if I have any trouble with further testing, but so far it looks great. Thank you so much for fixing this!

**Comment by gerlero** [comment]
Thank you! I'll make a new release with the fix.

**Comment by gregnordin** [comment]
I downloaded `openfoam2206-app-homebrew-arm64.zip` v1.8.2 from [Releases](https://github.com/gerlero/openfoam-app/releases), unzipped it, put the app in my `/Applications` directory, started it from the command line (iTerm2) with `$ /Applications/OpenFOAM-v2206.app/Contents/Resources/etc/openfoam`, and ran one of my simple test cases that uses `cartesianMesh` and `icoFoam`. After comparing the results with what I have gotten previously, everything checks out fine. Very nice job and thank you for all of your great work on this! 

P.S. The reason I directly downloaded the app rather than use Homebrew is it looks like Homebrew hasn't quite picked up the new version yet, which I assume will automatically get updated sometime in the near future:

```
$ brew info gerlero/openfoam/openfoam2206
==> openfoam2206: 1.8.1
https://github.com/gerlero/openfoam-app/
```

**Comment by gerlero** [comment]
You're welcome! Thanks for testing it.

I'm updating the Homebrew casks as I write this. The new version should be available in a few minutes (a `brew update` might be needed if Homebrew doesn't immediately pick it up).

**Comment by meteozond** [comment]
Hello! Sorry for writing into closed issue. 
I've just ran into the similar problem with my m1 at OpenFOAM-v2212:

1. `symbol not found` on source /Volumes/OpenFOAM-v2212/etc/bashrc && cartesianMesh 
2. `readonly file system` on /Volumes/OpenFOAM-v2212/etc/bashrc && /Volumes/OpenFOAM-v2212/Allwmake
3. `No such file or directory` when installing from FreeCAD-CfdOF

What is the correct way to get cfmesh on macos m1 with OpenFOAM.app?

**Comment by meteozond** [comment]
Thanks @gerlero I've already found that problem was with manualy built cfmesh. Built-in cfmesh works fine.
